"""
Baseline Django settings for RCD Nexus project. 

DO NOT put any deployment-specific configurations here! Import it into your deployment settings (e.g. rcd_nexus_settings.py) and override as needed.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import datetime
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# We're deploying behind a proxy in all cases
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    #
    # DJANGO APPS
    #
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    #
    # THIRD-PARTY APPS
    # Please document!
    #
    # OIDC (for CILogon, etc.)
    "mozilla_django_oidc",
    #
    #
    # In-house apps
    #
    "nexus",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "nexus.middleware.htmx",
]

ROOT_URLCONF = "nexus.routes"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "nexus.context_processors.base_template",
            ],
        },
    },
]

WSGI_APPLICATION = "nexus.deploy.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Things will probably break on anything except PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "localhost",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
    }
}

AUTH_USER_MODEL = "nexus.User"

# Authentication backends, such as local, OIDC, CAS, etc.
AUTHENTICATION_BACKENDS = (
    # local auth (admin site)
    "django.contrib.auth.backends.ModelBackend",
    # OIDC (e.g. CILogon)
    # "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
    "nexus.auth.CILogonOIDCAuthenticationBackend",
)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"
DEFAULT_USER_TIME_ZONE = "America/Denver"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Location that `collectstatic` will write to, and webserver will read from
STATIC_ROOT = Path("/var/cache/django/static")

# Media files (Uploads, etc)
MEDIA_ROOT = Path("/srv/www/django")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Needed for admin assessment view
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

LOGOUT_REDIRECT_URL = "/"

DEFAULT_FROM_EMAIL = "admin@portal.rcd-nexus.org"
SUPPORT_EMAIL = "capsmodel-help@carcc.org"
CURATOR_EMAIL = "capsmodel-owner@carcc.org"

# These options should be set in production.py
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://cilogon.org/authorize"
OIDC_OP_TOKEN_ENDPOINT = "https://cilogon.org/oauth2/token"
OIDC_OP_USER_ENDPOINT = "https://cilogon.org/oauth2/userinfo"
OIDC_OP_JWKS_ENDPOINT = "https://cilogon.org/oauth2/certs"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile org.cilogon.userinfo"
OIDC_AUTH_REQUEST_EXTRA_PARAMS = {
    "initialidp": "urn:mace:incommon:internet2.edu",  # So that invalid ORCID is not the default
}


RCD_DEFAULT_YEAR = datetime.date.today().year
