# Generated by Django 4.2.3 on 2023-10-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MOTD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="rcdprofile",
            name="open_access",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Open access profiles are visible to all users belonging to its primary institution (recommended).",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="mission",
            field=models.CharField(
                choices=[
                    (
                        "rsrchess",
                        "<b>Research Essential</b>: Research is the primary or exclusive mission,             and teaching does not significantly factor into faculty and institutional success                                                   (Research Labs, National Supercomputing Centers, etc.).",
                    ),
                    (
                        "rsrchfav",
                        "<b>Research Favored</b>: Research and teaching are the primary missions,             but research is what really drives faculty and institutional success (e.g., Research-driven Universities).",
                    ),
                    (
                        "balanced",
                        "<b>Balanced</b>: Research and teaching are both primary missions,             and they are equally important for faculty and institutional success.",
                    ),
                    (
                        "teachfav",
                        "<b>Teaching Favored</b>: Teaching is the primary mission,                                                 but faculty research is rewarded.",
                    ),
                    (
                        "teachess",
                        "<b>Teaching Essential</b>: Teaching is the primary mission,             and faculty research does not factor heavily in faculty and institutional success.",
                    ),
                ],
                default=None,
                help_text="Select the option that best describes your institution's mission.",
                max_length=64,
                null=True,
                verbose_name="Institutional Mission",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofilememberinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("contributor", "Contributor"),
                    ("manager", "Manager"),
                    ("submitter", "Submitter"),
                ],
                default="contributor",
                max_length=32,
            ),
        ),
    ]
