# Generated by Django 4.2.6 on 2024-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0002_motd_rcdprofile_open_access_alter_rcdprofile_mission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="ipeds_aanapisi_annh",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "AANAPISI or ANNH"), (2, "Not an AANAPISI or ANNH")],
                null=True,
                verbose_name="Asian American and Native American Pacific Islander Serving Institution and/or Alaska Native and Native Hawaiian Serving Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="ipeds_epscor",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "EPSCoR"), (2, "Not EPSCoR")],
                null=True,
                verbose_name="EPSCoR Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="ipeds_hsi",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "HSI"), (2, "Not an HSI")],
                null=True,
                verbose_name="Hispanic-Serving Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="ipeds_msi",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "An MSI"), (2, "Not an MSI")],
                null=True,
                verbose_name="Minority-Serving Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="ipeds_pbi",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "PBI"), (2, "Not a PBI")],
                null=True,
                verbose_name="Predominantly Black Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="ipeds_unitid",
            field=models.BigIntegerField(
                blank=True,
                help_text="IPEDS UnitID primarily for joining new data.",
                null=True,
                unique=True,
                verbose_name="IPEDS Unit ID",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="carnegie_classification",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (14, "Mixed Bacc/Assoc (Assoc. Dom.)"),
                    (15, "R1"),
                    (16, "R2"),
                    (17, "R3"),
                    (18, "M1"),
                    (19, "M2"),
                    (20, "M3"),
                    (21, "Bacc: Arts and Sci"),
                    (22, "Bacc: Diverse"),
                    (23, "Mixed Bacc/Assoc"),
                    (24, "4yr: Faith-Related Institutions"),
                    (25, "4yr: Med Schools & Centers"),
                    (26, "4yr: Other Health Prof. Schools"),
                    (27, "4yr: Research Institutions"),
                    (28, "4yr: Engineering & Technology Schools"),
                    (29, "4yr: Business & Management Schools"),
                    (30, "4yr: Arts, Music & Design Schools"),
                    (31, "4yr: Law Schools"),
                    (32, "4yr: Other Special Focus Institutions"),
                    (33, "Tribal Colleges"),
                ],
                null=True,
                verbose_name="Carnegie Classification",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="internet_domain",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="newinstitutionrequest",
            name="internet_domain",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="year",
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
