# Generated by Django 4.2.11 on 2024-09-11 19:31

import django.core.validators
from nexus.utils.data import merge_institutions
from django.core.exceptions import ValidationError
from django.db import migrations, models

def merge_institutions_by_pks(apps, pks, inst_name ):
    Institution = apps.get_model("nexus", "Institution")

    institutions = []
    print(f"merge_institutions_by_pks: {pks} with name: {inst_name}")
    for pk in pks:
        try:
            inst = Institution.objects.get(pk=pk, name__icontains=inst_name)
        except Institution.DoesNotExist:
            raise ValidationError(f"No institution found with for pk:[{pk}] and name matching ({inst_name}).")
        institutions.append(inst)
        
    base = merge_institutions(institutions)
    print(f"Merged institutions into base: {base.name} ({base.pk})")

def merge_duplicate_institutions(apps, schema_editor):
    # We need to fix duplicate institutions inadvertantly created by users. The list is: 
    # Case Western Reserve University (2 instances)
    # Used to test locally: merge_institutions_by_pks(apps, [1399, 2660], "Case Western Reserve University")
    merge_institutions_by_pks(apps, [305, 2662], "Case Western Reserve University")
    # Albert Einstein College of Medicine (2 instances)
    merge_institutions_by_pks(apps, [29, 2666], "Albert Einstein College of Medicine")
    # Massachusetts Institute of Technology (2 instances)
    merge_institutions_by_pks(apps, [981, 2144], "Massachusetts Institute of Technology")
    # University of Minnesota  (dupes University of Minnesota-Twin Cities)
    merge_institutions_by_pks(apps, [1837, 2149], "University of Minnesota")
    # Weill Cornell Medical College (dupes Weill Medical College of Cornell University)
    merge_institutions_by_pks(apps, [2036, 2143], "Weill")
    # Stony Brook University (2 instances)
    merge_institutions_by_pks(apps, [1555, 2140], "Stony Brook University")
    # University of North Carolina At Charlotte (2 instances)
    merge_institutions_by_pks(apps, [1862, 2693], "University of North Carolina At Charlotte")
    # South Dakota State University (2 instances)
    merge_institutions_by_pks(apps, [1466, 2132], "South Dakota State University")

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0003_institution_ipeds_aanapisi_annh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motd",
            name="dismissDays",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(30),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="carnegie_classification",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Unknown"),
                    (0, "Other RCD (Nat'l Labs/Facilities, etc.)"),
                    (14, "Mixed Bacc/Assoc (Assoc. Dom.)"),
                    (15, "R1"),
                    (16, "R2"),
                    (17, "R3"),
                    (18, "M1"),
                    (19, "M2"),
                    (20, "M3"),
                    (21, "Bacc: Arts and Sci"),
                    (22, "Bacc: Diverse"),
                    (23, "Mixed Bacc/Assoc"),
                    (24, "4yr: Faith-Related Institutions"),
                    (25, "4yr: Med Schools & Centers"),
                    (26, "4yr: Other Health Prof. Schools"),
                    (27, "4yr: Research Institutions"),
                    (28, "4yr: Engineering & Technology Schools"),
                    (29, "4yr: Business & Management Schools"),
                    (30, "4yr: Arts, Music & Design Schools"),
                    (31, "4yr: Law Schools"),
                    (32, "4yr: Other Special Focus Institutions"),
                    (33, "Tribal Colleges"),
                    (1000, "Miscellaneous (Funders, Agencies, etc.)"),
                    (1001, "Industry Labs/Institutes"),
                ],
                null=True,
                verbose_name="Institutional Classification",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="ipeds_region",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Service schools"),
                    (1, "New England"),
                    (2, "Mid East"),
                    (3, "Great Lakes"),
                    (4, "Plains"),
                    (5, "Southeast"),
                    (6, "Southwest"),
                    (7, "Rocky Mountains"),
                    (8, "Far West"),
                    (9, "Other U.S. jurisdictions"),
                    (100, "Canada"),
                    (200, "International"),
                ],
                null=True,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="mission",
            field=models.CharField(
                choices=[
                    (None, "Unknown"),
                    (
                        "rsrchess",
                        "<b>Research Essential</b>: Research is the primary or exclusive mission,             and teaching does not significantly factor into faculty and institutional success                                                   (Research Labs, National Supercomputing Centers, etc.).",
                    ),
                    (
                        "rsrchfav",
                        "<b>Research Favored</b>: Research and teaching are the primary missions,             but research is what really drives faculty and institutional success (e.g., Research-driven Universities).",
                    ),
                    (
                        "balanced",
                        "<b>Balanced</b>: Research and teaching are both primary missions,             and they are equally important for faculty and institutional success.",
                    ),
                    (
                        "teachfav",
                        "<b>Teaching Favored</b>: Teaching is the primary mission,                                                 but faculty research is rewarded.",
                    ),
                    (
                        "teachess",
                        "<b>Teaching Essential</b>: Teaching is the primary mission,             and faculty research does not factor heavily in faculty and institutional success.",
                    ),
                ],
                default=None,
                help_text="Select the option that best describes your institution's mission.",
                max_length=64,
                null=True,
                verbose_name="Institutional Mission",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="org_chart",
            field=models.CharField(
                choices=[
                    (None, "Unknown"),
                    ("infotech", "Information technology (e.g., CIO)"),
                    ("research", "Research (e.g., VPR)"),
                    ("academic", "Academic leadership (e.g., Provost or a Dean)"),
                    ("institute", "Academic/Research Institute or Center"),
                    ("other", "Other"),
                ],
                help_text="Select the option that best describes where within the institution your RCD program ultimately reports.              <br/>If 'Other', please explain in the comment section below.",
                max_length=32,
                null=True,
                verbose_name="Reporting structure",
            ),
        ),
    ]
