# Generated by Django 4.2.6 on 2024-04-12 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0003_institution_ipeds_aanapisi_annh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motd",
            name="dismissDays",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(30),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="carnegie_classification",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Unknown"),
                    (0, "Other RCD (Nat'l Labs/Facilities, etc.)"),
                    (14, "Mixed Bacc/Assoc (Assoc. Dom.)"),
                    (15, "R1"),
                    (16, "R2"),
                    (17, "R3"),
                    (18, "M1"),
                    (19, "M2"),
                    (20, "M3"),
                    (21, "Bacc: Arts and Sci"),
                    (22, "Bacc: Diverse"),
                    (23, "Mixed Bacc/Assoc"),
                    (24, "4yr: Faith-Related Institutions"),
                    (25, "4yr: Med Schools & Centers"),
                    (26, "4yr: Other Health Prof. Schools"),
                    (27, "4yr: Research Institutions"),
                    (28, "4yr: Engineering & Technology Schools"),
                    (29, "4yr: Business & Management Schools"),
                    (30, "4yr: Arts, Music & Design Schools"),
                    (31, "4yr: Law Schools"),
                    (32, "4yr: Other Special Focus Institutions"),
                    (33, "Tribal Colleges"),
                    (1000, "Miscellaneous (Funders, Agencies, etc.)"),
                    (1001, "Industry Labs/Institutes"),
                ],
                null=True,
                verbose_name="Institutional Classification",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="ipeds_region",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Service schools"),
                    (1, "New England"),
                    (2, "Mid East"),
                    (3, "Great Lakes"),
                    (4, "Plains"),
                    (5, "Southeast"),
                    (6, "Southwest"),
                    (7, "Rocky Mountains"),
                    (8, "Far West"),
                    (9, "Other U.S. jurisdictions"),
                    (100, "Canada"),
                    (200, "International"),
                ],
                null=True,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="mission",
            field=models.CharField(
                choices=[
                    (None, "Unknown"),
                    (
                        "rsrchess",
                        "<b>Research Essential</b>: Research is the primary or exclusive mission,             and teaching does not significantly factor into faculty and institutional success                                                   (Research Labs, National Supercomputing Centers, etc.).",
                    ),
                    (
                        "rsrchfav",
                        "<b>Research Favored</b>: Research and teaching are the primary missions,             but research is what really drives faculty and institutional success (e.g., Research-driven Universities).",
                    ),
                    (
                        "balanced",
                        "<b>Balanced</b>: Research and teaching are both primary missions,             and they are equally important for faculty and institutional success.",
                    ),
                    (
                        "teachfav",
                        "<b>Teaching Favored</b>: Teaching is the primary mission,                                                 but faculty research is rewarded.",
                    ),
                    (
                        "teachess",
                        "<b>Teaching Essential</b>: Teaching is the primary mission,             and faculty research does not factor heavily in faculty and institutional success.",
                    ),
                ],
                default=None,
                help_text="Select the option that best describes your institution's mission.",
                max_length=64,
                null=True,
                verbose_name="Institutional Mission",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="org_chart",
            field=models.CharField(
                choices=[
                    (None, "Unknown"),
                    ("infotech", "Information technology (e.g., CIO)"),
                    ("research", "Research (e.g., VPR)"),
                    ("academic", "Academic leadership (e.g., Provost or a Dean)"),
                    ("institute", "Academic/Research Institute or Center"),
                    ("other", "Other"),
                ],
                help_text="Select the option that best describes where within the institution your RCD program ultimately reports.              <br/>If 'Other', please explain in the comment section below.",
                max_length=32,
                null=True,
                verbose_name="Reporting structure",
            ),
        ),
    ]
