# Generated by Django 4.2.6 on 2025-03-04 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from nexus.models import SurveyReasonChoices

def populateSurveyReasons(apps, schema_editor):
    SurveyReason = apps.get_model("nexus", "SurveyReason")

    for choice in SurveyReasonChoices:
        SurveyReason.objects.get_or_create(reason=choice.value)

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0004_merge_institutions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "benchmarking",
                                "Benchmarking of current service offerings.",
                            ),
                            (
                                "stratplan",
                                "As part of (or an input to) Strategic Planning.",
                            ),
                            ("understanding", "To better understand common practices."),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="year",
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.CreateModel(
            name="PostCompletionSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labor_hours",
                    models.PositiveIntegerField(
                        help_text="Please include meetings (hours X the # of attendees) as well as individuals' effort to complete the assessment.",
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(400),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="About how many labor hours went into completing the assessment at your institution?",
                    ),
                ),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("nextyr", "Next year."),
                            ("two_three", "In two or three years."),
                            ("four_five", "In 4 or 5 years."),
                            ("unlikely", "Unlikely to complete another one in future"),
                        ],
                        default=None,
                        help_text="E.g., to assess progress on areas for improvement.",
                        max_length=32,
                        verbose_name="How soon would your institution likely complete a future Capabilities Model Assessment?",
                    ),
                ),
                (
                    "nps",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "0 Not at all Likely"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10 Extremely Likely"),
                        ],
                        default=None,
                        verbose_name="Based upon your experience, how likely are you to recommend the Capabilities Model Assessment tool to other institutions?",
                    ),
                ),
                ("reasons", models.ManyToManyField(to="nexus.surveyreason")),
            ],
        ),
        migrations.AddField(
            model_name="rcdprofile",
            name="survey",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="nexus.postcompletionsurvey",
            ),
        ),
        migrations.RunPython(populateSurveyReasons),
    ]
