# Generated by Django 4.2.6 on 2025-01-29 23:46

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0004_merge_institutions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitiesquestion",
            name="is_essential",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Whether this question is in the essential set.",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="year",
            field=models.PositiveIntegerField(default=2025),
        ),
        
    ]
