# Generated by Django 4.2.6 on 2024-09-06 17:17

from django.db import migrations
from nexus.utils.data import merge_institutions
from django.core.exceptions import ValidationError

def merge_institutions_by_pks(apps, pks, inst_name ):
    Institution = apps.get_model("nexus", "Institution")

    institutions = []
    print(f"merge_institutions_by_pks: {pks} with name: {inst_name}")
    for pk in pks:
        try:
            inst = Institution.objects.get(pk=pk, name__icontains=inst_name)
        except Institution.DoesNotExist:
            raise ValidationError(f"No institution found with for pk:[{pk}] and name matching ({inst_name}).")
        institutions.append(inst)
        
    base = merge_institutions(institutions)
    print(f"Merged institutions into base: {base.name} ({base.pk})")

def merge_duplicate_institutions(apps, schema_editor):
    # We need to fix duplicate institutions inadvertantly created by users. The list is: 
    # Case Western Reserve University (2 instances)
    # Used to test locally: merge_institutions_by_pks(apps, [1399, 2660], "Case Western Reserve University")
    merge_institutions_by_pks(apps, [305, 2662], "Case Western Reserve University")
    # Albert Einstein College of Medicine (2 instances)
    merge_institutions_by_pks(apps, [29, 2666], "Albert Einstein College of Medicine")
    # Massachusetts Institute of Technology (2 instances)
    merge_institutions_by_pks(apps, [981, 2144], "Massachusetts Institute of Technology")
    # University of Minnesota  (dupes University of Minnesota-Twin Cities)
    merge_institutions_by_pks(apps, [1837, 2149], "University of Minnesota")
    # Weill Cornell Medical College (dupes Weill Medical College of Cornell University)
    merge_institutions_by_pks(apps, [2036, 2143], "Weill")
    # Stony Brook University (2 instances)
    merge_institutions_by_pks(apps, [1555, 2140], "Stony Brook University")
    # University of North Carolina At Charlotte (2 instances)
    merge_institutions_by_pks(apps, [1862, 2693], "University of North Carolina At Charlotte")
    # South Dakota State University (2 instances)
    merge_institutions_by_pks(apps, [1466, 2132], "South Dakota State University")

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0004_motd_dismissdays_and_more"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_institutions, migrations.RunPython.noop)
    ]
