# Generated by Django 4.2.6 on 2025-01-30 00:45

import django.core.validators
from django.core.exceptions import ValidationError
from django.db import migrations, models
from nexus.models import CapabilitiesQuestion

def mark_question_essential(apps, qid):
    CapabilitiesQuestion = apps.get_model("nexus", "CapabilitiesQuestion")

    try:
        question = CapabilitiesQuestion.objects.get(attrs__legacy_qid=qid)
    except CapabilitiesQuestion.DoesNotExist:
        raise ValidationError(f"No CapabilitiesQuestion found with for qid:[{qid}].")
    question.is_essential = True
    question.save()
    print(f"Marked Question: {qid} as essential")

def mark_all_essential_questions(apps, schema_editor):
    essential_qids = ["R1.1", "R2.1", "R2.3", "R3.1", 
                      "D1.1", "D2.1", "D3.1", "D3.2", "D5.1", "D5.3", "D5.5", 
                      "SW1.1", "SW5.2", "SW6.1", "SW6.2", 
                      "SY1.1", "SY2.1", "SY2.2", "SY2.4", "SY2.5", "SY3.2", "SY4.1", "SY5.3", "SY8.4", "SY10.4", "SY11.1", 
                      "SP1.1", "SP1.5", "SP1.6", "SP1.7", "SP1.8", "SP2.1", "SP2.2", "SP3.1", "SP4.1", "SP5.1", "SP5.3", "SP6.1"]
    for qid in essential_qids:
        mark_question_essential(apps, qid)



class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0005_capabilitiesquestion_is_essential_and_more"),
    ]

    operations = [
        migrations.RunPython(mark_all_essential_questions),
    ]
