# Generated by Django 4.2.6 on 2025-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0005_surveyreason_alter_rcdprofile_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcompletionsurvey",
            name="nps",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not at all Likely"),
                    (1, ""),
                    (2, ""),
                    (3, ""),
                    (4, ""),
                    (5, ""),
                    (6, ""),
                    (7, ""),
                    (8, ""),
                    (9, ""),
                    (10, "Extremely Likely"),
                ],
                default=None,
                verbose_name="Based upon your experience, how likely are you to recommend the Capabilities Model Assessment tool to other institutions?",
            ),
        ),
        migrations.AlterField(
            model_name="postcompletionsurvey",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("nextyr", "Next year."),
                    ("two_three", "In two or three years."),
                    ("four_five", "In 4 or 5 years."),
                    ("unlikely", "Unlikely to complete another one in future"),
                ],
                default=None,
                help_text="E.g., to assess progress on areas for improvement.",
                max_length=32,
                verbose_name="How soon would your institution likely complete a future Capabilities Model Assessment?",
            ),
        ),
        migrations.AlterField(
            model_name="surveyreason",
            name="reason",
            field=models.CharField(
                choices=[
                    ("benchmarking", "Benchmarking of current service offerings."),
                    ("stratplan", "As part of (or an input to) Strategic Planning."),
                    ("understanding", "To better understand common practices."),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
