# Generated by Django 4.2.6 on 2025-01-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0006_auto_20250130_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitiesquestioncontent",
            name="shorttext",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="capabilitiesquestion",
            name="is_essential",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is in the essential set.",
            ),
        ),
    ]
