# Generated by Django 4.2.6 on 2025-02-26 18:19

from django.db import migrations
from nexus.models import SurveyReasonChoices


def populateSurveyReasons(apps, schema_editor):
    SurveyReason = apps.get_model("nexus", "SurveyReason")

    for choice in SurveyReasonChoices:
        SurveyReason.objects.get_or_create(reason=choice.value)

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0006_alter_postcompletionsurvey_nps_and_more"),
    ]

    operations = [
        migrations.RunPython(populateSurveyReasons),
    ]
