# Generated by Django 4.2.6 on 2025-02-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0008_auto_20250130_1857"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitiesassessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    (
                        "full",
                        "Conduct a <b>Full Assessment</b>, answering all the questions.                         This is the usual route for established RCD programs who want a full                        assessment of their capabilities.",
                    ),
                    (
                        "essential",
                        "Conduct an <b><em>Essentials</em> Assessment</b> answering                                     a subset of questions that has been identified for new and                                     emerging RCD programs who want to focus on the essential questions.",
                    ),
                    (
                        "cyoj",
                        "Conduct a <b><em>Chart Your Own Journey</em> Assessment</b>, selecting only                             those topics and questions that you want to focus on. This option is intended                             for RCD programs conducting a follow-up assessment who want to focus on just                             those areas that are likely to have changed since you last completed an assessment,                             or those that want to conduct a partial assessment of capabilities.",
                    ),
                ],
                default="full",
                help_text="Select the type of Assessment you would like to use.",
                max_length=32,
                null=True,
                verbose_name="Assessment Type",
            ),
        ),
        migrations.AddField(
            model_name="capabilitiesassessment",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derivative_copies",
                to="nexus.capabilitiesassessment",
            ),
        ),
    ]
