# Generated by Django 4.2.6 on 2025-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0009_capabilitiesassessment_assessment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitiesanswer",
            name="is_included",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is included in and Essentials or CYOJ assessment.",
            ),
        ),
        migrations.AlterField(
            model_name="capabilitiesassessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Assessment"),
                    ("essential", "Essentials Assessment"),
                    ("cyoj", "Chart Your Own Journey Assessment"),
                ],
                default="full",
                help_text="Select the type of Assessment you would like to use.",
                max_length=32,
                null=True,
                verbose_name="Assessment Type",
            ),
        ),
    ]
