# Generated by Django 4.2.6 on 2025-03-05 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0007_auto_20250226_1819"),
        ("nexus", "0010_capabilitiesanswer_is_included_and_more"),
    ]

    operations = []
