# Generated by Django 4.2.6 on 2026-04-28 22:09

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0011_merge_20250305_2246"),
    ]
    # Add support for unaccented search so we can find things like french named universities. 
    operations = [UnaccentExtension()]
