# Generated by Django 4.2.30 on 2026-06-30 23:39

from django.db import migrations
from nexus.utils.data import merge_institutions_by_pks
from django.db import migrations


def merge_duplicate_institutions_June2026(apps, schema_editor):
    merge_set = [
        [203, [2730], 'Boise State'],
        [258, [2738], 'San Luis Obispo'],
        [268, [2737], 'Fullerton'],
        [273, [2725], 'Sacramento'],
        [435, [2705], 'Cornell'],
        [648, [2707], 'Georgetown'],
        [652, [2704], 'Georgia Institute of Technology'],
        [819, [2702], 'Johns Hopkins'],
        [1221, [2723], 'Oregon Institute of Technology'],
        [1325, [2721], 'Rensselaer Polytechnic Institute'],
        [1330, [2712], 'Rice'],
        [1406, [2734], 'San Diego State'],
        [1595, [2696], 'Temple'],
        [1649, [2732], 'Tennessee'],
        [1704, [2695], 'Tulane'],
        [1749, [2724], 'Berkeley'],
        [1753, [2740], 'Los Angeles'],
        [1754, [2709], 'Merced'],
        [1761, [2706], 'Central Florida'],
        [1806, [2708], 'Louisville'],
        [1824, [2728], 'Amherst'],
        [1828, [2731], 'Memphis'],
        [1850, [2716], 'Las Vegas'],
        [1851, [2703], 'Reno'],
        [1857, [2736], 'New Mexico'],
        [1880, [2729], 'Oregon'],
        [1904, [2720], 'Richmond'],
        [1972, [2722], 'Wyoming'],
        [1979, [2735], 'Utah Valley'],
        [2682, [2727], 'Manitoba'],
        [2684, [2717], 'Toronto'],
        [2711, [2667,95], 'Arizona State'],
        [2714, [2085], 'William'],
        [305, [2662], 'Case Western'],
        [1466, [2132], 'South Dakota'],
        [2149, [1837], 'Minnesota'],
    ]
    for merge_item in merge_set:
           print(f"Calling merge_institutions_by_pks({merge_item[0]}, {merge_item[1]}, {merge_item[2]})")
           # no_merge=True during testing, verbose to get output of all changes implemented. 
           merge_institutions_by_pks(merge_item[0], merge_item[1], merge_item[2], no_merge=False, verbose=False )


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0012_auto_20260428_2209"),
    ]
    operations = [
         migrations.RunPython(merge_duplicate_institutions_June2026)
    ]
