# Generated by Django 4.2.30 on 2026-10-07 16:18

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def create_SupportStaff_GroupWithPerms(apps, schema_editor):
    support_perm_list = [
        # Allow viewing of users. Should be no need to edit or delete in normal support
        "view_user",
        # Allow viewing and editing of Institutions
        "view_institution", "change_institution", 
        # Allow viewing of new institution requests. Open question: Will we need change for approve actions?
        "view_newinstitutionrequest",
        # Allow viewing of Profiles
        "view_rcdprofile", "view_rcdprofilemember",
        "view_rcdprofilememberrequest",
        "view_rcdprofilememberinvite",
        # Allow viewing of Assessments and associated Models. Open question: Will we need change for approve actions?
        "view_capabilitiesassessment",
        "view_capabilitiesquestion", "view_capabilitiesquestioncontent",
        "view_capabilitiesanswer",
        "view_capabilitiestopic", "view_capabilitiestopiccontent",
        "view_facing", "view_facingcontent",
        # Allow viewing of surveys
        "view_postcompletionsurvey",
        # Allow viewing and editing of Message of the Day instances.
        "view_motd", "add_motd", "change_motd", "delete_motd",
        ]

    staff_group, created = Group.objects.get_or_create(name='SupportStaff')

    # Add the perms to the group
    for pname in support_perm_list:
        try:
            perm = Permission.objects.get(codename=pname)
        except Permission.DoesNotExist:
            print(f"Permission: {pname} not found. Check typos and rerun migration.")
        staff_group.permissions.add(perm)

    print(f"Group 'SupportStaff' " + "created" if created else "updated" + " with permissions.")
    # Note that we do not add users to the group. We will do that via the admin UI


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0013_auto_20260630_2339"),
    ]

    operations = [
             migrations.RunPython(create_SupportStaff_GroupWithPerms)
        ]
