# Generated by Django 4.2.30 on 2026-07-23 23:12

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime

def correctAssessmentCreateTimes(apps, schema_editor):
    CapabilitiesAssessment = apps.get_model("nexus", "CapabilitiesAssessment")
    field = CapabilitiesAssessment._meta.get_field('update_time')
    original_auto_now = field.auto_now
    field.auto_now = False

    for assmt in CapabilitiesAssessment.objects.all():
        creation_year = assmt.profile.year
        assumed_create_time = datetime(int(creation_year), 7, 1, tzinfo=timezone.utc)  # Pick a time before the 3.0 release
        if assmt.update_time < assumed_create_time:
            assumed_create_time = assmt.update_time
        assmt.create_time = assumed_create_time
        assmt.save()

    field.auto_now = original_auto_now


class Migration(migrations.Migration):
    dependencies = [
        ("nexus", "0014_auto_20260720_2010"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitiesassessment",
            name="create_time",
            field=models.DateTimeField(
                default=timezone.now,
                help_text="When the assessment was created.",
            ),
        ),
        migrations.AlterField(
            model_name="capabilitiesanswer",
            name="not_applicable",
            field=models.BooleanField(
                default=False,
                help_text="Check ONLY this if this capability is not at all applicable to your institution.",
                verbose_name="Capability not applicable",
            ),
        ),
        migrations.AlterField(
            model_name="capabilitiesanswer",
            name="work_notes",
            field=models.TextField(
                blank=True,
                help_text="Private work notes for this capability. Contents will not be included in the community datasets.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="capabilitiesquestion",
            name="valid_before",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="This question will only be included in assessments created before this time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcompletionsurvey",
            name="nps",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "0 Not at all Likely"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 Extremely Likely"),
                ],
                default=None,
                verbose_name="Based upon your experience, how likely are you to recommend the Capabilities Model Assessment tool to other institutions?",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="profile_reason",
            field=models.CharField(
                choices=[
                    ("rcdcmassess", "To create a Capabilities Model assessment"),
                    (
                        "simple",
                        "Just creating a simple profile for now (I'm exploring)",
                    ),
                    ("other", "Other"),
                ],
                default="rcdcmassess",
                help_text='If you are creating this profile other than to complete a Capabilities Model assessment (the default),             what is your reason for creating this profile (i.e., how do you intend to use it)?                 <br/>If "Other", please explain in the comment section below.',
                max_length=32,
                verbose_name="Reason for creating profile",
            ),
        ),
        migrations.AlterField(
            model_name="rcdprofile",
            name="year",
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.RunPython(correctAssessmentCreateTimes),
    ]
